import React,{useState,useMemo,useEffect,useRef,lazy,Suspense} from 'react';
import './studio.css';
import './components/studio/visualEditors.css';
import { ProjectData, TimeUnit } from './core/models/types';
import { DEFAULT_EKO_PROJECT } from './core/models/ekoProject';
import { DEFAULT_MOTOR_PROJECT,DEFAULT_BATTERY_PROJECT } from './core/models/defaultProjects';
import { parseProject } from './core/validation';
import { derive,newProject,download,filename,engineeringReport } from './core/project';
import { calculateTaktTime } from './core/algorithms/taktCalculator';
import { runLineBalancing } from './core/algorithms/lineBalancingEngine';
import { exportToDxf } from './core/export/dxfExporter';
import { spreadsheet,processRows,bomRows } from './core/export/excelImporter';
import { ProcessFlow } from './components/studio/ProcessFlow';
import { OperationRun } from './core/algorithms/networkSimulation';
import { ResourceEditor } from './components/studio/ResourceEditor';
import { topologicalSort } from './core/validation';
import { effectiveCycle } from './core/resources';
import { BalancingBoard } from './components/studio/BalancingBoard';
import { DataEditor } from './components/studio/DataEditors';
import { LayoutEditor } from './components/studio/LayoutEditor';
import { Simulation } from './components/studio/Simulation';
import { NumberField,Metric,fmt,formatTimeValue,formatTimeWithUnit,TIME_UNITS } from './components/studio/Fields';
import { StationWorkspace } from './components/studio/StationWorkspace';
import type { StationExportKind, StationExportSnapshot } from './components/studio/StationWorkspace';
import {archivedImportBlob, encodeImport} from './core/importArchive';
import {makePortableArchive, MAX_ARCHIVE_BYTES, readPortableArchive} from './core/portableArchive';
const Scene=lazy(()=>import('./components/studio/Scene').then(m=>({default:m.Scene})));
const KEY='layout-studio-v3',LIBRARY='layout-studio-scenarios-v3';
type Saved={id:string;name:string;at:string;project:ProjectData};
type HistoryEntry={project:ProjectData; importSourceBase64:string};
const exportLabels={archive:'archiwum v4',dxf:'DXF',balance:'bilans CSV',report:'raport MD',processXlsx:'proces XLSX',processCsv:'proces CSV',bomXlsx:'BOM XLSX',bomCsv:'BOM CSV'} as const;
type ExportKind='json'|keyof typeof exportLabels;
type DataExportKind='processXlsx'|'processCsv'|'bomXlsx'|'bomCsv';
type ExportRecord={project:ProjectData;source:string;at:string;dataSignature?:string};
const dataExportSignature=(kind:DataExportKind,project:ProjectData)=>JSON.stringify(kind.startsWith('process')?processRows(project.processSteps):bomRows(project.bom));
const dataExportKind=(kind:'process'|'bom',format:'xlsx'|'csv'):DataExportKind=>`${kind}${format==='xlsx'?'Xlsx':'Csv'}` as DataExportKind;
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);const legacy=v.project?.schemaVersion!==4;return {project:parseProject(JSON.stringify(v.project)),at:v.at as string,importSourceBase64:typeof v.importSourceBase64==='string'?v.importSourceBase64:'',warning:legacy?'Wykryto starszy zapis lokalny. Pobierz jego surową kopię, a następnie potwierdź migrację przed zapisaniem projektu w schemacie 4.':'',recoveryKind:legacy?'legacy' as const:null};}}catch(e){return {project:newProject(),at:'',importSourceBase64:'',warning:`Błąd zapisu lokalnego: ${(e as Error).message}. Pobierz kopię odzyskiwania przed zastąpieniem.`,recoveryKind:'corrupt' as const};}return {project:structuredClone({...DEFAULT_MOTOR_PROJECT,schemaVersion:4,algorithm:'RPW' as const,currency:'USD' as const}),at:'',importSourceBase64:'',warning:'',recoveryKind:null};}
const tabs=[['dashboard','Pulpit'],['demand','1 Popyt i takt'],['process','2 Proces'],['flow','2a Przepływ'],['bom','3 BOM'],['balance','4 Bilans'],['layout','5 Hala i CAD'],['simulation','6 3D i symulacja'],['report','7 Raport'],['stations','Stanowiska v5']] as const;
const help=[['Takt klienta','Dostępny czas po przerwach / dzienne zapotrzebowanie.'],['Cel cyklu po OEE','Takt klienta × OEE. Rezerwa na straty używana przy bilansowaniu.'],['VA / NVA','Czas dodający wartość / pozostały czas. Suma to czas standardowy.'],['RPW','Priorytet według czasu operacji oraz wszystkich unikalnych następców.'],['LCR','Priorytet według malejącego czasu operacji, z zachowaniem zależności.'],['WIP','Sztuki w systemie, które weszły do linii i nie ukończyły ostatniej stacji.'],['Spaghetti','Łamana między środkami stanowisk, bez omijania przeszkód.']];
export function App(){
  const [initial]=useState(load),[raw,setRaw]=useState(initial.project),[importSourceBase64,setImportSourceBase64]=useState(initial.importSourceBase64),[tab,setTab]=useState<string>('dashboard'),[message,setMessage]=useState(initial.warning),[savedAt,setSavedAt]=useState(initial.at),[saveError,setSaveError]=useState(initial.warning),[allowSave,setAllowSave]=useState(!initial.warning),[recoveryDownloaded,setRecoveryDownloaded]=useState(false),[dirty,setDirty]=useState(false),[exportRecords,setExportRecords]=useState<Partial<Record<ExportKind,ExportRecord>>>({});
  const [past,setPast]=useState<HistoryEntry[]>([]),[future,setFuture]=useState<HistoryEntry[]>([]),[modal,setModal]=useState<{message:string;action:()=>void}|null>(null),[library,setLibrary]=useState<Saved[]>(()=>{try{const v=JSON.parse(localStorage.getItem(LIBRARY)??'[]');return Array.isArray(v)?v:[];}catch{return [];}}),[scenarioName,setScenarioName]=useState('Wariant 1'),[scenarioExportIds,setScenarioExportIds]=useState<string[]>([]);
  const [activeRuns,setActiveRuns]=useState<OperationRun[]>([]);
  const [simulationExportKey,setSimulationExportKey]=useState<string|null>(null);
  const [stationSimulationExportKey,setStationSimulationExportKey]=useState<string|null>(null);
  const [stationExportSnapshots,setStationExportSnapshots]=useState<Partial<Record<StationExportKind,StationExportSnapshot>>>({});
  const [printRequest,setPrintRequest]=useState<{project:ProjectData;at:string}|null>(null);
  const file=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),autosaveTimer=useRef<number|undefined>(undefined);
  const {project:p,issues}=useMemo(()=>derive(raw),[raw]);const t=calculateTaktTime(p.demand),b=p.balancing;const unit=p.timeUnit??'s';
  const notify=(m:string)=>setMessage(m);
  const markExport=(kind:ExportKind)=>setExportRecords(records=>({...records,[kind]:{project:raw,source:importSourceBase64,at:new Date().toISOString(),dataSignature:kind==='processXlsx'||kind==='processCsv'||kind==='bomXlsx'||kind==='bomCsv'?dataExportSignature(kind,p):undefined}}));
  const markStationExport=(kind:StationExportKind,snapshot:StationExportSnapshot)=>setStationExportSnapshots(records=>({...records,[kind]:snapshot}));
  const isExportCurrent=(kind:ExportKind)=>{
    const record=exportRecords[kind];if(!record)return false;
    if(kind==='processXlsx'||kind==='processCsv'||kind==='bomXlsx'||kind==='bomCsv')return record.dataSignature===dataExportSignature(kind,p);
    return record.project===raw&&(kind!=='archive'||record.source===importSourceBase64);
  };
  const dataExportStatus=(kind:'process'|'bom',format:'xlsx'|'csv')=>{const key=dataExportKind(kind,format);return exportRecords[key]?isExportCurrent(key)?'aktualny':'nieaktualny — pobierz ponownie':'—';};
  const printReport=()=>{try{window.print();setPrintRequest({project:raw,at:new Date().toISOString()});}catch(e){notify(`Nie otwarto drukowania: ${(e as Error).message}`);}};
  const change=(next:ProjectData,nextImportSourceBase64=importSourceBase64)=>{setPast(h=>[...h.slice(-39),{project:raw,importSourceBase64}]);setFuture([]);setRaw({...next,updatedAt:new Date().toISOString()});setImportSourceBase64(nextImportSourceBase64);setDirty(true);};
  const confirm=(message:string,action:()=>void)=>setModal({message,action});
  useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);
  const writeSave=(project:ProjectData,source=importSourceBase64,reportFailure=true)=>{if(!allowSave)return false;try{parseProject(JSON.stringify(project));}catch{if(reportFailure)setSaveError('Błędy danych: popraw je, aby zapisać. Poprzedni poprawny zapis zachowany.');return false;}try{const at=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify({project,at,importSourceBase64:source}));setSavedAt(at);setDirty(false);setSaveError('');return true;}catch{if(reportFailure)setSaveError(source?'Brak miejsca lub dostępu do pamięci przeglądarki. Pobierz pierwotny import i wyeksportuj projekt JSON.':'Brak miejsca lub dostępu do pamięci przeglądarki. Wyeksportuj JSON.');return false;}};
  useEffect(()=>{if(!allowSave)return;setDirty(true);const id=window.setTimeout(()=>writeSave(raw),700);autosaveTimer.current=id;return()=>{window.clearTimeout(id);if(autosaveTimer.current===id)autosaveTimer.current=undefined;};},[raw,importSourceBase64,allowSave]);
  useEffect(()=>{const h=(e:BeforeUnloadEvent)=>{if(dirty||saveError){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty,saveError]);
  const replace=(project:ProjectData)=>confirm('Zastąpić bieżący projekt? Możesz wrócić przyciskiem Cofnij. Warto wcześniej wyeksportować JSON.',()=>{change({...structuredClone(project),id:crypto.randomUUID()},'');setTab('demand');notify('Projekt gotowy. Kopię przenośną zachowasz przyciskiem Eksport JSON.');});
  const json=()=>{download(JSON.stringify({...p,schemaVersion:4},null,2),`${filename(p)}.json`,'application/json');markExport('json');notify(`Przekazano ${filename(p)}.json do pobrania. Sprawdź folder pobierania w przeglądarce.`);};
  const portableJson=async()=>{try{const checked=parseProject(JSON.stringify({...p,schemaVersion:4}));if(importSourceBase64)parseProject(await archivedImportBlob(importSourceBase64).text());download(makePortableArchive(4,checked,importSourceBase64),`${filename(p)}_archiwum_v4.json`,'application/json');markExport('archive');notify('Przekazano przenośne archiwum projektu 4 do pobrania.');}catch(e){notify(`Nie utworzono archiwum: ${(e as Error).message}`);}};
  const dxf=()=>{const perform=()=>{download(exportToDxf(p.facility,p.layoutObjects,p.name,p.obstacles),`${filename(p)}.dxf`,'application/dxf');markExport('dxf');notify(`Przekazano ${filename(p)}.dxf do pobrania. Jednostki: mm, przeszkody: warstwa OBSTACLES.`);};if(issues.length)confirm('Projekt ma błędy lub kolizje. Wyeksportować roboczy DXF mimo uwag?',perform);else perform();};
  const importJson=async(f:File)=>{try{if(f.size>MAX_ARCHIVE_BYTES)throw new Error('Maksymalny plik archiwum: 25 MB.');const bytes=new Uint8Array(await f.arrayBuffer());const text=new TextDecoder().decode(bytes);const archive=readPortableArchive(text,4);if(!archive&&f.size>10*1024*1024)throw new Error('Maksymalny zwykły JSON: 10 MB.');const candidate=parseProject(archive?JSON.stringify(archive.project):text);if(archive?.importSourceBase64)parseProject(await archivedImportBlob(archive.importSourceBase64).text());const source=archive?archive.importSourceBase64:encodeImport(bytes);confirm(`Wczytać projekt „${candidate.name}”? Bieżący projekt możesz przywrócić przez Cofnij.`,()=>{if(!allowSave){notify('Import nie zastąpił projektu. Najpierw pobierz kopię odzyskiwania i włącz zapis.');return;}const next={...candidate,updatedAt:new Date().toISOString()};if(!writeSave(next,source,false)){notify('Import nie zastąpił bieżącego projektu: brak miejsca lub dostępu do pamięci przeglądarki. Zwolnij miejsce lub wybierz mniejszy plik.');return;}window.clearTimeout(autosaveTimer.current);setPast(h=>[...h.slice(-39),{project:raw,importSourceBase64}]);setFuture([]);setRaw(next);setImportSourceBase64(source);setTab('dashboard');notify(archive?'Wczytano i zapisano przenośne archiwum projektu.':'Wczytano i zapisano projekt oraz pierwotny plik.');});}catch(e){notify(`Import odrzucony: ${(e as Error).message}`);}};
  const saveScenario=()=>{if(!scenarioName.trim()){notify('Podaj nazwę wariantu.');return;}try{parseProject(JSON.stringify(p));const list=[...library,{id:crypto.randomUUID(),name:scenarioName.trim(),at:new Date().toISOString(),project:structuredClone(p)}];if(list.length>20)throw new Error('Limit: 20 wariantów.');localStorage.setItem(LIBRARY,JSON.stringify(list));setLibrary(list);notify('Zapisano wariant w tej przeglądarce.');}catch(e){notify(`Nie zapisano wariantu: ${(e as Error).message}`);}};
  const exportScenario=(s:Saved)=>{download(JSON.stringify(s.project,null,2),`${s.name.replace(/[^\p{L}\p{N}_-]/gu,'_')}.json`,'application/json');setScenarioExportIds(ids=>ids.includes(s.id)?ids:[...ids,s.id]);notify(`Przekazano JSON wariantu „${s.name}” do pobrania. Sprawdź folder pobierania.`);};
  const undo=()=>{if(!past.length)return;setFuture([{project:raw,importSourceBase64},...future]);setRaw(past[past.length-1].project);setImportSourceBase64(past[past.length-1].importSourceBase64);setPast(past.slice(0,-1));};
  const redo=()=>{if(!future.length)return;setPast([...past,{project:raw,importSourceBase64}]);setRaw(future[0].project);setImportSourceBase64(future[0].importSourceBase64);setFuture(future.slice(1));};
  const errorArea=(areas:string[])=>issues.some(i=>i.severity==='error'&&areas.includes(i.area));
  const ready:Record<string,boolean>={demand:!errorArea(['demand']),process:!!p.processSteps.length&&!errorArea(['process']),flow:!!p.processSteps.length&&!errorArea(['process']),bom:!errorArea(['bom']),balance:!!b?.workstations.length&&!b.workstations.some(s=>s.isBottleneck),layout:!!p.layoutObjects.length&&!issues.some(i=>['facility','layout'].includes(i.area)),simulation:!!b?.workstations.length,report:!!b?.workstations.length&&!issues.length};
  const exportBalance=()=>{if(!b)return;spreadsheet(b.workstations.map(s=>({'Stanowisko':s.id,'Operacje':s.assignedStepIds.join(', '),'Cykl zespołu [s]':s.cycleTimeSeconds,'Kopie':s.parallelStations??1,'Obsada na kopię':s.operators??1,'Odstęp zdolności [s]':effectiveCycle(s),'Cel [s]':b.taktTimeSeconds,'Obciążenie [%]':effectiveCycle(s)/b.taktTimeSeconds*100,'Status':s.isBottleneck?'PRZEKROCZENIE':'W NORMIE'})),`${filename(p)}_Bilans`,'csv');markExport('balance');notify('Przekazano raport bilansu CSV do pobrania.');};
  const staleExports=(Object.keys(exportLabels) as (keyof typeof exportLabels)[]).filter(kind=>exportRecords[kind]&&!isExportCurrent(kind)).map(kind=>exportLabels[kind]);
  return <div className="studio"><header className="studio-header"><div className="brand">LAYOUT STUDIO <span>Pro 3D · 0.4.0</span></div><label className="project-name">Nazwa projektu<input aria-label="Nazwa projektu" value={raw.name} onChange={e=>change({...raw,name:e.target.value})}/></label><label className="project-name">Jednostka czasu<select aria-label="Jednostka czasu" value={p.timeUnit??'s'} onChange={e=>change({...p,timeUnit:e.target.value as TimeUnit})}>{TIME_UNITS.map(u=><option key={u.value} value={u.value}>{u.label}</option>)}</select></label><div className="toolbar"><button disabled={!past.length} onClick={undo}>Cofnij</button><button disabled={!future.length} onClick={redo}>Ponów</button><button onClick={()=>{if(writeSave(raw))notify('Zapisano lokalnie. JSON pozwala przenieść projekt.');}}>Zapisz lokalnie</button><button className="primary" onClick={json}>Eksport JSON</button><button onClick={portableJson}>Eksport archiwum v4</button><button disabled={!importSourceBase64} onClick={()=>download(archivedImportBlob(importSourceBase64),'Pierwotnie_importowany_projekt.json')}>Pobierz pierwotny import</button><button disabled={!p.layoutObjects.length} onClick={dxf}>Eksport DXF</button></div></header>
  <div className="save-bar"><span className={saveError?'bad':''}>{saveError||(dirty?'Niezapisane zmiany…':`Zapis lokalny: ${savedAt?new Date(savedAt).toLocaleString('pl-PL'):'oczekuje'}`)}</span><span className={exportRecords.json&&!isExportCurrent('json')?'bad':''}>Eksport JSON w sesji: {exportRecords.json?`${new Date(exportRecords.json.at).toLocaleTimeString('pl-PL')} · ${isExportCurrent('json')?'aktualny':'nieaktualny — pobierz ponownie'}`:'—'}</span>{staleExports.length>0&&<span className="bad">Pobierz ponownie: {staleExports.join(', ')}</span>}{printRequest&&printRequest.project!==raw&&<span className="bad">Dane zmienione od ostatniego wywołania drukowania — uruchom druk ponownie.</span>}</div>
  {!allowSave&&<div className="notice"><button onClick={()=>{const original=localStorage.getItem(KEY);if(original===null){notify('Nie znaleziono zapisu do pobrania.');return;}download(original,initial.recoveryKind==='legacy'?'Starszy_zapis_lokalny.json':'Odzyskiwanie_zapisu.json','application/json');setRecoveryDownloaded(true);}}>{initial.recoveryKind==='legacy'?'Pobierz starszy zapis':'Pobierz kopię odzyskiwania'}</button><button disabled={initial.recoveryKind==='legacy'&&!recoveryDownloaded} onClick={()=>confirm(initial.recoveryKind==='legacy'?'Zastąpić starszy zapis lokalny projektem w schemacie 4? Upewnij się, że pobrana kopia jest dostępna.':'Zezwolić na zastąpienie uszkodzonego zapisu bieżącym projektem?',()=>setAllowSave(true))}>{initial.recoveryKind==='legacy'?'Potwierdź migrację i zapis':'Włącz zapis'}</button></div>}
  <nav className="studio-nav" aria-label="Etapy projektu">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)} aria-current={tab===id?'step':undefined}>{label}{id!=='dashboard'&&id!=='stations'&&<span title={ready[id]?'Dane gotowe':'Wymaga danych lub kontroli'}>{ready[id]?' ✓':' ○'}</span>}</button>)}</nav>
  {message&&<div className="message" role="status"><span>{message}</span><button aria-label="Zamknij komunikat" onClick={()=>setMessage('')}>×</button></div>}
  <main>
  {tab==='dashboard'&&<section className="page"><p className="eyebrow">PROJEKTOWANIE LINII PRODUKCYJNYCH</p><h1>{p.name}</h1><p className="muted">Od popytu do bilansu operacji, planu hali i symulacji partii.</p><div className="cards"><button className="action-card" onClick={()=>replace(newProject())}><strong>Rozpocznij od zera</strong><span>Pusty proces i BOM, własne założenia.</span></button><button className="action-card" onClick={()=>replace({...DEFAULT_MOTOR_PROJECT,algorithm:'RPW',currency:'USD'})}><strong>Przykład — silniki EV</strong><span>Sześć operacji, BOM i układ U.</span></button><button className="action-card" onClick={()=>replace({...DEFAULT_BATTERY_PROJECT,algorithm:'RPW',currency:'USD'})}><strong>Przykład — baterie EV</strong><span>Sześć operacji i przepływ liniowy.</span></button><button className="action-card" onClick={()=>replace(DEFAULT_EKO_PROJECT)}><strong>Przykład — Eko, rybia ość</strong><span>16 operacji. Montaż drzwi i paneli równolegle. Czasy nowych etapów, hala i popyt są testowe.</span></button><button className="action-card" onClick={()=>file.current?.click()}><strong>Importuj projekt JSON lub archiwum v4</strong><span>Wczytaj kopię przenośną z walidacją.</span></button></div>
  <div className="metrics"><Metric label="Operacje" value={String(p.processSteps.length)}/><Metric label="Pracochłonność" value={`${formatTimeWithUnit(b?.totalWorkContentSeconds, unit)}/szt.`}/><Metric label="Stanowiska" value={String(b?.actualWorkstationsCount??0)}/><Metric label="Materiały" value={String(p.bom.length)}/></div>
  <h2>Warianty projektu</h2><p className="muted">Zapisuj wariant przed zmianą popytu lub organizacji linii. Warianty pozostają w tej przeglądarce; JSON służy do archiwizacji. Zapisany wariant jest osobną migawką — późniejsze zmiany bieżącego projektu nie zmieniają jego JSON.</p><div className="toolbar"><input aria-label="Nazwa wariantu" value={scenarioName} onChange={e=>setScenarioName(e.target.value)}/><button onClick={saveScenario}>Zapisz wariant</button></div><div className="table-wrap"><table><thead><tr><th>Wariant</th><th>Cel cyklu [{unit}]</th><th>Stacje</th><th>Sprawność</th><th>Układ</th><th>Akcje</th></tr></thead><tbody>{library.map(s=>{let q:ProjectData|undefined;try{q=derive(s.project).project;}catch{}return <tr key={s.id}><td>{s.name}<small>{new Date(s.at).toLocaleString('pl-PL')}</small></td><td>{formatTimeValue(q?.balancing?.taktTimeSeconds, unit)}</td><td>{q?.balancing?.actualWorkstationsCount??'—'}</td><td>{fmt(q?.balancing?.lineEfficiencyPercent)}%</td><td>{q?.targetLayoutType}</td><td><button onClick={()=>{try{replace(parseProject(JSON.stringify(s.project)));}catch(e){notify((e as Error).message);}}}>Wczytaj</button><button onClick={()=>exportScenario(s)}>JSON</button><button className="danger" onClick={()=>confirm(`Usunąć wariant ${s.name}?`,()=>{try{const next=library.filter(x=>x.id!==s.id);localStorage.setItem(LIBRARY,JSON.stringify(next));setLibrary(next);}catch{notify('Błąd pamięci lokalnej.');}})}>Usuń</button>{scenarioExportIds.includes(s.id)&&<small role="status">JSON przekazany do pobrania w tej sesji · migawka wariantu</small>}</td></tr>;})}</tbody></table></div>
  <h2>Słownik i założenia</h2><div className="help-grid">{help.map(([term,desc])=><details key={term}><summary>{term}</summary><p>{desc}</p></details>)}</div></section>}
  {tab==='demand'&&<section className="page"><h1>Popyt i organizacja pracy</h1><p className="muted">Ustal wymagania klienta, dostępny czas pracy i rezerwę OEE.</p><div className="panel form-grid">{([['yearlyDemand','Popyt roczny [szt.]',1,1000000000],['workingDaysPerYear','Dni robocze w roku',1,366],['shiftsPerDay','Liczba zmian na dobę',1,3],['hoursPerShift','Godziny na zmianę',.01,24],['plannedBreaksMinutesPerShift','Przerwy na zmianę [min]',0,1440],['oeePercent','OEE / dostępność [%]',.01,100]] as const).map(([key,label,min,max])=><NumberField key={key} label={label} min={min} max={max} step={key==='workingDaysPerYear'||key==='shiftsPerDay'?'1':'any'} value={p.demand[key]} onChange={v=>change({...p,demand:{...p.demand,[key]:v}})}/>)}</div><div className="metrics"><Metric label="Popyt dzienny" value={`${fmt(t.dailyDemand)} szt.`}/><Metric label="Takt klienta" value={`${formatTimeWithUnit(t.customerTaktSeconds, unit)}/szt.`} hint="Czas po przerwach / popyt"/><Metric label="Cel cyklu po OEE" value={`${formatTimeWithUnit(t.taktTimeSeconds, unit)}/szt.`} hint="Takt × OEE; cel bilansu"/><Metric label="Tempo efektywne" value={`${fmt(t.requiredPartsPerHour)} szt./h`}/></div><div style={{display:'flex',gap:'1rem',alignItems:'flex-end'}}><label className="field">Waluta kosztów BOM<select value={p.currency??'USD'} onChange={e=>change({...p,currency:e.target.value as ProjectData['currency']})}>{['PLN','EUR','USD'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Jednostka czasu prezentacji<select aria-label="Jednostka czasu prezentacji" value={p.timeUnit??'s'} onChange={e=>change({...p,timeUnit:e.target.value as TimeUnit})}>{TIME_UNITS.map(u=><option key={u.value} value={u.value}>{u.label}</option>)}</select></label></div><p className="muted">Zmiana waluty zmienia oznaczenie, nie przelicza cen. Zmiana jednostki czasu przelicza pola i wskaźniki bez modyfikacji bazowych sekund w modelu. OEE jest założeniem planistycznym.</p></section>}
  {(tab==='process'||tab==='bom')&&<DataEditor key={`${tab}-${p.id}`} kind={tab} project={p} change={change} notify={notify} confirm={confirm} onExport={format=>markExport(dataExportKind(tab,format))} exportStatus={{xlsx:dataExportStatus(tab,'xlsx'),csv:dataExportStatus(tab,'csv')}}/>}
  {tab==='flow'&&<section className="page"><h1>Przepływ procesu</h1><ProcessFlow project={p} change={change} confirm={confirm}/></section>}
  {tab==='balance'&&<section className="page"><h1>Bilansowanie i Yamazumi</h1><p className="muted">Obsada i równoległe kopie są edytowalne. Operacje niepodzielne. Heurystyki respektują zależności, lecz nie gwarantują minimum globalnego.</p><div className="toolbar"><label>Metoda <select aria-label="Metoda bilansowania" value={p.algorithm??'RPW'} onChange={e=>{const algorithm=e.target.value as ProjectData['algorithm'];const steps=algorithm==='Manual'?p.processSteps.map(s=>({...s,assignedWorkstationId:b?.workstations.find(w=>w.assignedStepIds.includes(s.id))?.id??s.assignedWorkstationId})):p.processSteps;change({...p,algorithm,processSteps:steps});}}><option value="RPW">RPW — wagi pozycyjne</option><option value="LCR">LCR — najdłuższe operacje</option><option value="Manual">Ręczne przypisanie</option></select></label><button disabled={!b} onClick={exportBalance}>Eksport bilansu CSV</button></div>
  {p.algorithm==='Manual'&&<details className="panel"><summary>Zaawansowane przypisania ręczne</summary><p>Stanowiska od 1, bez luk. Poprzednik nie może być na późniejszej stacji.</p><div className="form-grid">{p.processSteps.map(s=><NumberField key={s.id} label={`${s.id} — ${s.name}`} min={1} max={p.processSteps.length} step="1" value={Number(s.assignedWorkstationId?.replace('WS-',''))||1} onChange={v=>change({...p,processSteps:p.processSteps.map(x=>x.id===s.id?{...x,assignedWorkstationId:`WS-${v}`} :x)})}/>)}</div></details>}
  {!b?.workstations.length?<p className="empty">Dodaj poprawne operacje i ustaw popyt. Błędy znajdziesz poniżej.</p>:<><div className="metrics"><Metric label="Stanowiska" value={String(b.actualWorkstationsCount)} hint={`Obsada: ${b.workstations.reduce((n,s)=>n+(s.operators??1)*(s.parallelStations??1),0)} osób. Minimum bazowe: ${b.theoreticalMinWorkstations}`}/><Metric label="Sprawność bilansu" value={`${fmt(b.lineEfficiencyPercent)}%`} hint="Suma cykli zespołów / (kopie × max(cel, odstęp zdolności))"/><Metric label="Odstęp wąskiego gardła" value={formatTimeWithUnit(b.bottleneckCycleTimeSeconds, unit)}/><Metric label="Zdolność efektywna" value={`${fmt(t.netOperatingSecondsPerDay/b.bottleneckCycleTimeSeconds)} szt./dzień`}/></div>
  <button onClick={()=>confirm("Przypisać każdą operację do osobnego stanowiska? Dotychczasowe grupowanie zostanie zastąpione.",()=>change({...p,algorithm:"Manual",processSteps:topologicalSort(p.processSteps).map((s,i)=>({...s,assignedWorkstationId:`WS-${i+1}`}))}))}>Każda operacja osobno — zachowaj gałęzie</button><BalancingBoard project={p} change={change}/><ResourceEditor project={p} change={change}/>
  <h2>Wąskie gardła</h2>{b.workstations.some(s=>s.isBottleneck)?b.workstations.filter(s=>s.isBottleneck).map(s=><p className="error" key={s.id}>{s.name}: +{formatTimeWithUnit(effectiveCycle(s)-b.taktTimeSeconds, unit)} ponad cel. Zmniejsz czas, rozdziel operację technologicznie lub przeanalizuj obsadę.</p>):<p className="success">Każde stanowisko mieści się w docelowym cyklu.</p>}
  <details><summary>Porównaj RPW i LCR</summary><div className="metrics">{(['RPW','LCR'] as const).map(a=>{try{const r=runLineBalancing(p.processSteps,t.taktTimeSeconds,a);return <Metric key={a} label={a} value={`${r.actualWorkstationsCount} stacji`} hint={`Sprawność ${fmt(r.lineEfficiencyPercent)}%`}/>;}catch{return null;}})}</div></details></>}
  </section>}
  {tab==='layout'&&<><div className="layout-choice"><label>Typ układu <select aria-label="Typ układu" value={p.targetLayoutType} onChange={e=>{const targetLayoutType=e.target.value as ProjectData['targetLayoutType'];if(p.layoutMode==='manual')confirm('Zmiana typu zastąpi ręczne pozycje. Kontynuować?',()=>change({...p,targetLayoutType,layoutMode:'auto'}));else change({...p,targetLayoutType});}}><option value="ProcessFlow">Z procesu — gałęzie / rybia ość</option><option value="UShape">U-Shape</option><option value="Linear">Liniowy</option><option value="LShape">L-Shape</option></select></label></div><LayoutEditor project={p} change={change} confirm={confirm}/></>}
  {tab==='simulation'&&<section className="page"><h1>Hala 3D i symulacja</h1>{errorArea(['demand','process','facility','layout'])||!b?.workstations.length?<><p className="empty">Najpierw popraw proces, popyt i halę. Symulacja wymaga poprawnego bilansu.</p>{simulationExportKey&&<p className="error" role="status">Nie można potwierdzić aktualności pobranego CSV symulacji. Po poprawieniu danych sprawdź wynik i pobierz raport ponownie.</p>}</>:<><Suspense fallback={<p>Wczytywanie 3D…</p>}><Scene project={p} change={change} activeRuns={activeRuns}/></Suspense><Simulation key={JSON.stringify([p.processSteps,p.demand,p.algorithm,p.workstationSettings])} project={p} notify={notify} onActive={setActiveRuns} exportedResultKey={simulationExportKey} onExportResult={setSimulationExportKey}/></>}</section>}
  {tab==='report'&&<section className="page"><h1>Raport i przekazanie projektu</h1><p>Sprawdź kontrolę projektu poniżej. JSON zachowuje dane i ustawienia, DXF zawiera geometrię w mm wraz z przeszkodami.</p><div className="toolbar"><button onClick={json}>Kompletny projekt JSON</button><button disabled={!p.layoutObjects.length} onClick={dxf}>Rzut DXF</button><button disabled={!b} onClick={exportBalance}>Bilans CSV</button><button onClick={()=>{download(engineeringReport(p,issues),`${filename(p)}_Raport.md`);markExport('report');notify('Przekazano edytowalny raport Markdown do pobrania.');}}>Raport inżynierski MD</button><button onClick={printReport}>Drukuj / zapisz PDF</button></div>{printRequest&&<p role="status" className={printRequest.project===raw?'muted':'bad'}>{printRequest.project===raw?`Wywołano drukowanie dla tej wersji o ${new Date(printRequest.at).toLocaleTimeString('pl-PL')}. Sprawdź w przeglądarce, czy PDF został zapisany.`:'Dane zmieniły się od ostatniego wywołania drukowania. Drukuj ponownie i sprawdź zapis PDF.'}</p>}<pre className="report-preview">{engineeringReport(p,issues)}</pre></section>}
  {tab==='stations'&&<StationWorkspace legacyProject={raw} legacyImportSourceBase64={importSourceBase64} simulationExportKey={stationSimulationExportKey} onSimulationExport={setStationSimulationExportKey} exportSnapshots={stationExportSnapshots} onExportSnapshot={markStationExport}/>}
  {tab!=='stations'&&<section className="validation"><details open={issues.some(i=>i.severity==='error')}><summary>Kontrola projektu — {issues.filter(i=>i.severity==='error').length} błędów, {issues.filter(i=>i.severity==='warning').length} ostrzeżeń</summary>{!issues.length?<p className="success">Nie wykryto błędów danych ani kolizji wyposażenia.</p>:<ul>{issues.map((i,n)=><li key={n} className={i.severity==='error'?'bad':'warn'}>{i.message}</li>)}</ul>}</details></section>}
  {tab!=='stations'&&<div className="footer-nav">{tab!=='dashboard'&&<button onClick={()=>setTab(tabs[Math.max(0,tabs.findIndex(t=>t[0]===tab)-1)][0])}>← Poprzedni etap</button>}{tab!=='report'&&<button className="primary" onClick={()=>setTab(tabs[tabs.findIndex(t=>t[0]===tab)+1][0])}>Następny etap →</button>}</div>}
  </main><input ref={file} hidden type="file" accept=".json" onChange={e=>{if(e.target.files?.[0])void importJson(e.target.files[0]);e.target.value='';}}/>
  <dialog ref={dialog} onCancel={()=>setModal(null)} aria-labelledby="confirm-title"><h2 id="confirm-title">Potwierdź zmianę</h2><p>{modal?.message}</p><div className="toolbar"><button autoFocus onClick={()=>setModal(null)}>Anuluj</button><button className="primary" onClick={()=>{const action=modal?.action;setModal(null);action?.();}}>Potwierdź</button></div></dialog>
  </div>;
}
export default App;
