import React,{useState,useRef,useEffect} from 'react';
import { ProjectData,ProcessStep,BOMComponent } from '../../core/models/types';
import { processErrors,topologicalSort,validateProject } from '../../core/validation';
import { importProcess,importBOM,processRows,bomRows,spreadsheet,exportTemplate,PROCESS_COLUMN_DOCS,BOM_COLUMN_DOCS } from '../../core/export/excelImporter';
import { NumberField,TextField,TimeField,fmt,formatTimeValue,formatTimeWithUnit } from './Fields';
import { setOperationLinks, successorsOf, updateProcess, replaceImportedProcess, removeOperation } from '../../core/editing';
import { ProcessFlow } from './ProcessFlow';

type Props={project:ProjectData;change:(p:ProjectData)=>void;notify:(m:string)=>void;confirm:(message:string,action:()=>void)=>void;onExport:(format:'xlsx'|'csv')=>void;exportStatus:{xlsx:string;csv:string}};
const blankStep=():ProcessStep=>({id:'',name:'',standardTimeSeconds:40,vaTimeSeconds:34,nvaTimeSeconds:6,sequenceNumber:1,predecessorIds:[]});
const blankBom=():BOMComponent=>({id:crypto.randomUUID(),name:'',partNumber:'',quantityPerUnit:1,container:'BoxKLT',packageQuantity:20,associatedProcessStepId:'',unitCost:0});

export function DataEditor({project:p,change,notify,confirm,kind,onExport,exportStatus}:{kind:'process'|'bom'}&Props){
  const isProcess=kind==='process',file=useRef<HTMLInputElement>(null);
  const [step,setStep]=useState(blankStep),[bom,setBom]=useState(blankBom),[editing,setEditing]=useState<string|null>(null),[diagram,setDiagram]=useState(false),[error,setError]=useState(''),[report,setReport]=useState('');
  const [pred,setPred]=useState(''),[succ,setSucc]=useState('');
  const resetEditor=()=>{setEditing(null);setStep(blankStep());setBom(blankBom());setPred('');setSucc('');setError('');};
  // Undo/redo and diagram changes must not leave a stale form able to overwrite the restored data.
  useEffect(()=>{
    if(!editing)return;
    if(isProcess){
      const current=p.processSteps.find(s=>s.id===editing);
      if(!current){resetEditor();return;}
      setStep({...current});setPred(current.predecessorIds.join(', '));setSucc(successorsOf(p.processSteps,current.id).join(', '));
    }else{
      const current=p.bom.find(b=>b.id===editing);
      if(!current){resetEditor();return;}
      setBom({...current});
    }
    setError('');
  },[editing,isProcess,p.processSteps,p.bom]);
  const commitStep=(candidate:ProcessStep)=>{
    if(!editing&&p.algorithm==='Manual')candidate={...candidate,assignedWorkstationId:'WS-'+Math.max(1,...p.processSteps.filter(s=>candidate.predecessorIds.includes(s.id)).map(s=>Number(s.assignedWorkstationId?.replace('WS-',''))||1))};
    let items=editing?p.processSteps.map(s=>s.id===editing?candidate:s):[...p.processSteps,{...candidate,sequenceNumber:p.processSteps.length+1}];
    try{items=setOperationLinks(items,candidate.id,candidate.predecessorIds,succ.split(/[,;]/).map(x=>x.trim()).filter(Boolean));}catch(e){setError((e as Error).message);return;}
    const errors=processErrors(items);if(errors.length){setError(errors.join('\n'));return;}
    try{change(updateProcess(p,items));}catch(e){setError((e as Error).message);return;}setStep(blankStep());setEditing(null);setPred('');setSucc('');setError('');notify('Zapisano operację.');
  };
  const save=(e:React.FormEvent)=>{e.preventDefault();if(isProcess){commitStep({...step,id:step.id.trim(),name:step.name.trim(),predecessorIds:pred.split(/[,;]/).map(x=>x.trim()).filter(Boolean)});return;}
    const candidate={...bom,name:bom.name.trim(),partNumber:bom.partNumber.trim()};
    const items=editing?p.bom.map(b=>b.id===editing?candidate:b):[...p.bom,candidate];
    const errors=validateProject({...p,bom:items}).filter(i=>i.area==='bom');if(errors.length){setError(errors.map(i=>i.message).join('\n'));return;}
    change({...p,bom:items});setBom(blankBom());setEditing(null);setError('');notify('Zapisano materiał.');
  };
  const remove=(id:string)=>confirm(isProcess?`Usunąć operację ${id}? Usunięte zostaną też powiązania poprzedników. Materiały przypisane do operacji wymagają ponownego przypisania. Możesz użyć Cofnij.`:'Usunąć materiał? Możesz użyć Cofnij.',()=>{
    try{
      change(isProcess?removeOperation(p,id,false):{...p,bom:p.bom.filter(b=>b.id!==id)});
      if(editing===id)resetEditor();
      notify(isProcess?'Usunięto operację i jej połączenia. BOM zachowano; sprawdź przypisania materiałów. Dostępne Cofnij.':'Usunięto materiał. Dostępne Cofnij.');
    }catch(e){setError((e as Error).message);}
  });
  const upload=async(f:File)=>{try{if(f.size>10*1024*1024)throw new Error('Limit pliku: 10 MB.');const data=await f.arrayBuffer();const r=isProcess?importProcess(data):importBOM(data,new Set(p.processSteps.map(s=>s.id)));setReport(`Odczytane: ${r.read}, poprawne: ${r.items.length}, pominięte: ${r.skipped}.\n${r.errors.join('\n')}`);if(r.errors.length){notify('Import odrzucony. Popraw błędy w raporcie; dane projektu zachowane.');return;}confirm(`Import zastąpi ${isProcess?'operacje':'BOM'} (${r.items.length} wierszy). ${isProcess?'Przydziały i zasoby zostaną przeliczone od nowa metodą RPW. BOM i geometria ręczna pozostaną zachowane. ':''}Kontynuować?`,()=>{change(isProcess?replaceImportedProcess(p,r.items as ProcessStep[]):{...p,bom:r.items as BOMComponent[]});resetEditor();notify('Import zakończony. Dostępne Cofnij.');});}catch(e){setReport((e as Error).message);}};
  const exportData=(template:boolean,format:'xlsx'|'csv')=>{const name=`${template?'Szablon':'Eksport'}_${kind}`;if(template){exportTemplate(kind,format);notify(`Przekazano ${name}.${format} do pobrania. Folder pobierania zależy od ustawień przeglądarki.`);return;}const rows=isProcess?processRows(p.processSteps):bomRows(p.bom);if(!rows.length){notify('Brak danych do eksportu.');return;}spreadsheet(rows,name,format);onExport(format);notify(`Przekazano ${name}.${format} do pobrania. Folder pobierania zależy od ustawień przeglądarki.`);};
  const unit=p.timeUnit??'s';
  return <section className="page"><h1>{isProcess?'Proces i operacje':'Materiały BOM'}</h1><p className="muted">{isProcess?`Zbuduj graf zależności. Operacje są niepodzielne; czasy podawaj w ${unit==='s'?'sekundach':unit==='min'?'minutach':'godzinach'}.`:'Powiąż materiały z operacjami i oblicz zapotrzebowanie logistyczne.'}</p>
    <div className="toolbar"><button onClick={()=>file.current?.click()}>Import Excel / CSV</button><button onClick={()=>exportData(false,'xlsx')}>Eksport XLSX</button><button onClick={()=>exportData(false,'csv')}>Eksport CSV</button><button onClick={()=>exportData(true,'xlsx')}>Szablon XLSX</button><button onClick={()=>exportData(true,'csv')}>Szablon CSV</button>{isProcess&&<><button onClick={()=>setDiagram(!diagram)}>{diagram?'Tabela':'Diagram'}</button><button onClick={()=>{try{change({...p,processSteps:topologicalSort(p.processSteps)});notify('Uporządkowano operacje według zależności.');}catch(e){notify((e as Error).message);}}}>Uporządkuj sekwencję</button></>}</div>
    {(exportStatus.xlsx!=='—'||exportStatus.csv!=='—')&&<p role="status" className={exportStatus.xlsx.startsWith('nieaktualny')||exportStatus.csv.startsWith('nieaktualny')?'bad':'muted'}>Eksporty danych w tej sesji: XLSX {exportStatus.xlsx}; CSV {exportStatus.csv}. Szablony są stałe i niezależne od projektu.</p>}
    <input hidden ref={file} type="file" accept=".xlsx,.csv" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/>
    <details><summary>Format importu i specyfikacja kolumn (szablon XLSX i CSV)</summary><p>Importowany jest pierwszy arkusz pliku Excel lub plik CSV. Wiersz 1 zawiera nagłówki, kolejne wiersze dane. Szablon XLSX zawiera dwa arkusze: <strong>Dane</strong> (gotowy przykład wielogałęziowy do uzupełnienia) oraz <strong>Opis kolumn</strong> (specyfikacja wymagań, typów i jednostek). Plik z błędami jest odrzucany w całości, a projekt pozostaje nienaruszony.</p><div className="table-wrap"><table><thead><tr><th>Kolumna</th><th>Status</th><th>Typ danych</th><th>Jednostka</th><th>Opis i zasady walidacji</th></tr></thead><tbody>{(isProcess?PROCESS_COLUMN_DOCS:BOM_COLUMN_DOCS).map(col=><tr key={col['Kolumna']}><td><strong>{col['Kolumna']}</strong></td><td><span className={col['Status']==='Wymagana'?'badge-req':'badge-opt'}>{col['Status']}</span></td><td>{col['Typ']}</td><td>{col['Jednostka']}</td><td>{col['Opis']}</td></tr>)}</tbody></table></div><p className="muted">{isProcess?'Wskazówka: ID tekstowe (np. OP10, OP20) chronią przed modyfikacją zer wiodących przez Excel. Połączenia z kolumn Poprzednicy i Następnicy są sumowane w relacje procesu. Domyślny podział czasu: 85% VA i 15% NVA.':'Wskazówka: Każdy komponent musi być przypisany do istniejącego ID operacji procesu. Dopuszczalne typy pojemników: BoxKLT, Pallet, Tray, Carton.'}</p></details>
    {report&&<pre className="notice" role="status">{report}</pre>}
    <form className="panel" onSubmit={save}><h2>{editing?'Edytuj':'Dodaj'} {isProcess?'operację':'materiał'}</h2><div className="form-grid">
      {isProcess?<><label className="field">ID operacji<input required value={step.id} disabled={!!editing} onChange={e=>setStep({...step,id:e.target.value})}/></label><TextField label="Nazwa operacji" value={step.name} onChange={name=>setStep({...step,name})}/><TimeField label="Czas standardowy" min={0.001} seconds={step.standardTimeSeconds} unit={unit} onChange={v=>{const ratio=step.standardTimeSeconds>0?step.vaTimeSeconds/step.standardTimeSeconds:.85;const va=Number((v*ratio).toFixed(4));setStep({...step,standardTimeSeconds:v,vaTimeSeconds:va,nvaTimeSeconds:Number((v-va).toFixed(4))});}}/><TimeField label="VA wartość dodana" seconds={step.vaTimeSeconds} unit={unit} max={step.standardTimeSeconds} onChange={v=>setStep({...step,vaTimeSeconds:v,nvaTimeSeconds:Number((step.standardTimeSeconds-v).toFixed(4))})}/><label className="field">Poprzednicy (ID, po przecinku)<input value={pred} onChange={e=>setPred(e.target.value)} placeholder="OP10, OP20"/></label><label className="field">Następnicy (ID, po przecinku)<input value={succ} onChange={e=>setSucc(e.target.value)} placeholder="OP05, OP30"/></label></>:<><TextField label="Numer części" value={bom.partNumber} onChange={v=>setBom({...bom,partNumber:v})}/><TextField label="Nazwa materiału" value={bom.name} onChange={name=>setBom({...bom,name})}/><NumberField label="Ilość na wyrób" min={0.0001} value={bom.quantityPerUnit} onChange={quantityPerUnit=>setBom({...bom,quantityPerUnit})}/><NumberField label="Ilość w opakowaniu" min={1} step="1" value={bom.packageQuantity} onChange={packageQuantity=>setBom({...bom,packageQuantity})}/><NumberField label={`Koszt jednostkowy [${p.currency??'USD'}]`} value={bom.unitCost} onChange={unitCost=>setBom({...bom,unitCost})}/><label className="field">Pojemnik<select value={bom.container} onChange={e=>setBom({...bom,container:e.target.value as BOMComponent['container']})}>{['BoxKLT','Pallet','Tray','Carton'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Operacja<select required value={bom.associatedProcessStepId} onChange={e=>setBom({...bom,associatedProcessStepId:e.target.value})}><option value="">Wybierz operację</option>{p.processSteps.map(s=><option key={s.id} value={s.id}>{s.id} — {s.name}</option>)}</select></label></>}
    </div>{isProcess&&<p className="muted">NVA (czas bez wartości dodanej): {formatTimeWithUnit(step.nvaTimeSeconds, unit)}. Zmiana czasu zachowuje obecną proporcję VA/NVA; VA można zmienić ręcznie.</p>}{error&&<pre className="error" role="alert">{error}</pre>}<div className="toolbar"><button className="primary" type="submit">{editing?'Zapisz zmiany':'Dodaj'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setStep(blankStep());setBom(blankBom());setPred('');setSucc('');setError('');}}>Anuluj edycję</button>}</div></form>
    {diagram&&isProcess?<ProcessFlow project={p} change={change} confirm={confirm}/>:<div className="table-wrap"><table><thead><tr>{(isProcess?['ID','Operacja',`Czas [${unit}]`,`VA / NVA [${unit}]`,'Poprzednicy','Następnicy','Akcje']:['Część','Materiał','Ilość/szt.','Opakowanie','Operacja','Koszt/szt.','Zużycie/dzień','Pojemniki/zmianę','Akcje']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{isProcess?p.processSteps.map(s=><tr key={s.id}><td>{s.id}</td><td>{s.name}</td><td>{formatTimeValue(s.standardTimeSeconds, unit)}</td><td>{formatTimeValue(s.vaTimeSeconds, unit)} / {formatTimeValue(s.nvaTimeSeconds, unit)}</td><td>{s.predecessorIds.join(', ')||'—'}</td><td>{successorsOf(p.processSteps,s.id).join(', ')||'—'}</td><td><button onClick={()=>{setStep({...s});setPred(s.predecessorIds.join(', '));setSucc(successorsOf(p.processSteps,s.id).join(', '));setEditing(s.id);setError('');}}>Edytuj</button><button className="danger" onClick={()=>remove(s.id)}>Usuń</button></td></tr>):p.bom.map(b=><tr key={b.id}><td>{b.partNumber}</td><td>{b.name}</td><td>{fmt(b.quantityPerUnit)}</td><td>{b.container} / {b.packageQuantity}</td><td>{b.associatedProcessStepId}</td><td>{fmt(b.unitCost*b.quantityPerUnit)} {p.currency}</td><td>{fmt(b.quantityPerUnit*p.demand.yearlyDemand/p.demand.workingDaysPerYear)}</td><td>{fmt(Math.ceil(b.quantityPerUnit*p.demand.yearlyDemand/p.demand.workingDaysPerYear/p.demand.shiftsPerDay/b.packageQuantity),0)}</td><td><button onClick={()=>{setBom({...b});setEditing(b.id);setError('');}}>Edytuj</button><button className="danger" onClick={()=>remove(b.id)}>Usuń</button></td></tr>)}</tbody></table>{(isProcess?p.processSteps:p.bom).length===0&&<p className="empty">Brak danych. Dodaj pierwszy wiersz lub pobierz i uzupełnij szablon.</p>}</div>}
    {!isProcess&&<p className="notice">Koszt materiałów: {fmt(p.bom.reduce((n,b)=>n+b.unitCost*b.quantityPerUnit,0))} {p.currency??'USD'}/szt. Pojemniki zaokrąglono w górę; obliczenie nie uwzględnia zapasu bezpieczeństwa.</p>}
  </section>;
}
