import React,{useRef,useState} from 'react';
import { ProjectData,LayoutObject,Obstacle } from '../../core/models/types';
import { defaultLayoutSettings,corners } from '../../core/algorithms/layoutEngine';
import { layoutRoutes } from '../../core/algorithms/routing';
import { NumberField,TextField } from './Fields';

type Props={project:ProjectData;change:(p:ProjectData)=>void;confirm:(m:string,a:()=>void)=>void};
export function LayoutEditor({project:p,change,confirm}:Props){
  const [selected,setSelected]=useState(''),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[moveMode,setMoveMode]=useState(false),[snap,setSnap]=useState(true),[draft,setDraft]=useState<LayoutObject|null>(null),[obs,setObs]=useState<Obstacle|null>(null);
  const [preview,setPreview]=useState<LayoutObject|null>(null);
  const svg=useRef<SVGSVGElement>(null),drag=useRef<{x:number;y:number;id?:string;startX:number;startY:number}|null>(null);
  const settings=p.layoutSettings??defaultLayoutSettings;
  const all=[...p.layoutObjects,...p.obstacles];const pts=all.flatMap(o=>corners(o));
  const minX=Math.min(0,...pts.map(o=>o.x))-1000,minY=Math.min(0,...pts.map(o=>o.y))-1000;
  const maxX=Math.max(p.facility.widthMm,...pts.map(o=>o.x))+1000,maxY=Math.max(p.facility.lengthMm,...pts.map(o=>o.y))+1000;
  const w=(maxX-minX)/zoom,h=(maxY-minY)/zoom;
  const point=(e:React.PointerEvent)=>{const s=svg.current!,pt=s.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(s.getScreenCTM()!.inverse());};
  const saveObject=(e:React.FormEvent)=>{e.preventDefault();if(!draft)return;change({...p,layoutMode:'manual',layoutObjects:p.layoutObjects.some(o=>o.id===draft.id)?p.layoutObjects.map(o=>o.id===draft.id?draft:o):[...p.layoutObjects,draft]});setDraft(null);};
  const saveObs=(e:React.FormEvent)=>{e.preventDefault();if(!obs)return;change({...p,obstacles:p.obstacles.some(o=>o.id===obs.id)?p.obstacles.map(o=>o.id===obs.id?obs:o):[...p.obstacles,obs]});setObs(null);};
  const num=(label:string,key:keyof ProjectData['facility'])=><NumberField key={key} label={label} min={100} max={500000} value={p.facility[key]} onChange={v=>change({...p,facility:{...p.facility,[key]:v}})}/>;
  return <section className="page"><h1>Hala i edytor CAD 2D</h1><p className="muted">Wymiary w milimetrach. Wybierz obiekt na rzucie, aby zmienić jego geometrię. Przesuwanie wyposażenia włącza tryb ręczny.</p>
  <div className="panel"><div className="form-grid">{num('Szerokość hali [mm]','widthMm')}{num('Długość hali [mm]','lengthMm')}{num('Wysokość hali [mm]','heightMm')}{num('Siatka [mm]','gridSizeMm')}</div><details><summary>Parametry automatycznego layoutu</summary><div className="form-grid">{([['tableWidthMm','Szerokość stołu'],['tableLengthMm','Głębokość stołu'],['spacingMm','Odstęp wzdłuż linii'],['aisleMm','Przejście / odstęp ramion']] as const).map(([key,label])=><NumberField key={key} label={`${label} [mm]`} min={100} value={settings[key]} onChange={v=>change({...p,layoutSettings:{...settings,[key]:v}})}/>)}</div><p>Generator centruje układ w hali. Każda stacja otrzymuje stół, regał FIFO i strefę operatora. Wejście i wyjście umieszczane są przy krańcowych stacjach. Tryb „Z procesu” wyznacza główną nitkę na podstawie skumulowanego czasu i rozkłada gałęzie obok niej. Fioletowe połączenia pokazują zależności. Układ nie omija automatycznie przeszkód — kolizje są raportowane. Zmiana parametrów działa od razu w trybie automatycznym.</p></details></div>
  <div className="toolbar"><button onClick={()=>setZoom(Math.min(8,zoom*1.3))} title="Przybliż rzut">Przybliż +</button><button onClick={()=>setZoom(Math.max(.3,zoom/1.3))} title="Oddal rzut">Oddal −</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>Dopasuj cały layout</button><button aria-pressed={moveMode} onClick={()=>setMoveMode(!moveMode)}>{moveMode?'Przesuwaj obiekty':'Przesuwaj widok'}</button><label><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/> Przyciąganie do siatki</label><button onClick={()=>confirm('Ponowne generowanie zastąpi ręczne pozycje i wymiary wyposażenia. Kontynuować?',()=>{change({...p,layoutMode:'auto'});setDraft(null);})}>Generuj automatycznie</button><span>Tryb: {p.layoutMode==='manual'?'ręczny':'automatyczny'}</span></div>
  <div className="toolbar"><button onClick={()=>setDraft({id:`EQ-${crypto.randomUUID().slice(0,8)}`,name:'Dodatkowe wyposażenie',type:'QualityGate',xMm:1000,yMm:1000,zMm:0,widthMm:1000,lengthMm:1000,heightMm:1800,rotationDeg:0,colorHex:'#8b5cf6'})}>Dodaj wyposażenie</button>{selected&&p.layoutObjects.find(o=>o.id===selected)&&<button className="danger" onClick={()=>confirm('Usunąć wybrany obiekt? Usunięcie stołu stanowiska wymaga ponownej generacji layoutu przed symulacją.',()=>{change({...p,layoutMode:'manual',layoutObjects:p.layoutObjects.filter(o=>o.id!==selected)});setSelected('');setDraft(null);})}>Usuń wybrany obiekt</button>}</div>
  <svg ref={svg} role="img" aria-label="Rzut hali i wyposażenia" className="cad-canvas" viewBox={`${minX+pan.x} ${minY+pan.y} ${w} ${h}`} onPointerDown={e=>{const q=point(e);drag.current={x:q.x,y:q.y,startX:pan.x,startY:pan.y};svg.current?.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d?.id)return;const q=point(e),grid=snap?p.facility.gridSizeMm:1;const original=p.layoutObjects.find(o=>o.id===d.id)!;setPreview({...original,xMm:Math.round((d.startX+q.x-d.x)/grid)*grid,yMm:Math.round((d.startY+q.y-d.y)/grid)*grid});}} onPointerUp={e=>{setPreview(null);const d=drag.current;if(!d)return;const q=point(e);if(d.id){const step=snap?p.facility.gridSizeMm:1;const x=Math.round((d.startX+q.x-d.x)/step)*step,y=Math.round((d.startY+q.y-d.y)/step)*step;change({...p,layoutMode:'manual',layoutObjects:p.layoutObjects.map(o=>o.id===d.id?{...o,xMm:x,yMm:y}:o)});setDraft(null);}else setPan({x:d.startX-(q.x-d.x),y:d.startY-(q.y-d.y)});drag.current=null;}} onPointerCancel={()=>{drag.current=null;setPreview(null);}}>
    <defs><pattern id="cad-grid" width={Math.max(100,p.facility.gridSizeMm||1000)} height={Math.max(100,p.facility.gridSizeMm||1000)} patternUnits="userSpaceOnUse"><path d={`M ${p.facility.gridSizeMm} 0 L 0 0 0 ${p.facility.gridSizeMm}`} fill="none" stroke="#334155" strokeWidth="10"/></pattern></defs>
    <rect x={0} y={0} width={p.facility.widthMm||1} height={p.facility.lengthMm||1} fill="url(#cad-grid)" stroke="#94a3b8" strokeWidth="35"/>
    <text x={0} y={-250} fill="#cbd5e1" fontSize="300">Hala {p.facility.widthMm} × {p.facility.lengthMm} mm</text>
    {layoutRoutes(p).map(({a,b},i)=><line key={'route'+i} x1={a.xMm+a.widthMm/2} y1={a.yMm+a.lengthMm/2} x2={b.xMm+b.widthMm/2} y2={b.yMm+b.lengthMm/2} stroke='#c084fc' strokeWidth='35' pointerEvents='none'/>)}
    {p.layoutObjects.map(original=>{const o=preview?.id===original.id?preview:original;return <g key={o.id} onPointerDown={e=>{e.stopPropagation();setSelected(o.id);setDraft({...o});if(moveMode){const q=point(e);drag.current={x:q.x,y:q.y,id:o.id,startX:o.xMm,startY:o.yMm};svg.current?.setPointerCapture(e.pointerId);}}}><polygon points={corners(o).map(c=>`${c.x},${c.y}`).join(' ')} fill={o.colorHex} stroke={selected===o.id?'#fff':'#94a3b8'} strokeWidth={selected===o.id?70:15}/><text x={o.xMm+80} y={o.yMm+220} fill="white" fontSize="160" pointerEvents="none">{o.workstationId??o.id}</text><title>{o.name}: {o.widthMm} × {o.lengthMm} mm</title></g>;})}
    {p.obstacles.map(o=><g key={o.id} onPointerDown={e=>{e.stopPropagation();setObs({...o});}}><rect x={o.xMm} y={o.yMm} width={o.widthMm} height={o.lengthMm} fill="#dc2626"/><text x={o.xMm} y={o.yMm-80} fill="#fca5a5" fontSize="180">{o.name}</text></g>)}
  </svg><p className="legend">🔵 Stanowiska · 🟠 FIFO · 🟢 Operator / wyroby · 🟣 Wejście · 🔴 Przeszkody. Przeciągnij i puść, aby przesunąć; przybliżenie przyciskami.</p>
  {draft&&<form className="panel" onSubmit={saveObject}><h2>Obiekt {draft.id}</h2><div className="form-grid"><TextField label="Nazwa obiektu" value={draft.name} onChange={name=>setDraft({...draft,name})}/>{(['xMm','yMm','widthMm','lengthMm','heightMm','rotationDeg'] as const).map((key,i)=><NumberField key={key} label={['X [mm]','Y [mm]','Szerokość [mm]','Głębokość [mm]','Wysokość [mm]','Obrót [stopnie]'][i]} value={draft[key]} min={key==='rotationDeg'?-360:key==='xMm'||key==='yMm'?-500000:1} max={500000} onChange={v=>setDraft({...draft,[key]:v})}/>)}</div><button className="primary">Zapisz obiekt</button><button type="button" onClick={()=>setDraft(null)}>Zamknij</button></form>}
  <div className="toolbar"><h2>Przeszkody i strefy wyłączone</h2><button onClick={()=>setObs({id:crypto.randomUUID(),name:'Nowa przeszkoda',xMm:1000,yMm:1000,widthMm:800,lengthMm:800,heightMm:3000})}>Dodaj przeszkodę</button></div>
  {obs&&<form className="panel" onSubmit={saveObs}><div className="form-grid"><TextField label="Nazwa przeszkody" value={obs.name} onChange={name=>setObs({...obs,name})}/>{(['xMm','yMm','widthMm','lengthMm','heightMm'] as const).map((key,i)=><NumberField key={key} label={['X [mm]','Y [mm]','Szerokość [mm]','Głębokość [mm]','Wysokość [mm]'][i]} value={obs[key]} min={i<2?0:1} max={500000} onChange={v=>setObs({...obs,[key]:v})}/>)}</div><button className="primary">Zapisz przeszkodę</button><button type="button" onClick={()=>setObs(null)}>Anuluj</button></form>}
  <div className="table-wrap"><table><thead><tr><th>Nazwa</th><th>X / Y [mm]</th><th>Wymiary [mm]</th><th>Akcje</th></tr></thead><tbody>{p.obstacles.map(o=><tr key={o.id}><td>{o.name}</td><td>{o.xMm} / {o.yMm}</td><td>{o.widthMm} × {o.lengthMm} × {o.heightMm}</td><td><button onClick={()=>setObs({...o})}>Edytuj</button><button className="danger" onClick={()=>confirm(`Usunąć przeszkodę ${o.name}?`,()=>change({...p,obstacles:p.obstacles.filter(x=>x.id!==o.id)}))}>Usuń</button></td></tr>)}</tbody></table></div>
  <details><summary>Lista wyposażenia</summary><div className="table-wrap"><table><thead><tr><th>ID</th><th>Nazwa</th><th>X / Y [mm]</th><th>Wymiary [mm]</th><th>Akcja</th></tr></thead><tbody>{p.layoutObjects.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.name}</td><td>{o.xMm} / {o.yMm}</td><td>{o.widthMm} × {o.lengthMm}</td><td><button onClick={()=>{setDraft({...o});setSelected(o.id);}}>Edytuj</button></td></tr>)}</tbody></table></div></details>
  </section>;
}
